# -*- coding: utf-8 -*-
# Generated by Django 1.9 on 2018-10-18 15:05
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Anuncio',
            fields=[
                ('id_anuncio', models.IntegerField(primary_key=True, serialize=False)),
                ('titulo_anuncio', models.CharField(max_length=250)),
                ('alter_titulo_anuncio', models.CharField(blank=True, max_length=250, null=True)),
                ('detalle_anuncio', models.CharField(max_length=600)),
                ('alter_detalle_anuncio', models.CharField(blank=True, max_length=600, null=True)),
                ('fecha_anuncio', models.DateTimeField()),
                ('fecha_cierre_anuncio', models.DateTimeField(blank=True, null=True)),
                ('estado_anuncio', models.IntegerField()),
            ],
            options={
                'db_table': 'anuncio',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='EstadoPostulacion',
            fields=[
                ('id_estado_postulacion', models.AutoField(primary_key=True, serialize=False)),
                ('desc_estado_postulacion', models.CharField(max_length=45)),
            ],
            options={
                'db_table': 'estado_postulacion',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='Postulacion',
            fields=[
                ('id_postulacion', models.AutoField(primary_key=True, serialize=False)),
                ('fecha_postulacion', models.DateTimeField()),
                ('fecha_cambio_postulacion', models.DateTimeField()),
            ],
            options={
                'db_table': 'postulacion',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='TipoAnuncio',
            fields=[
                ('id_tipo_anuncio', models.IntegerField(primary_key=True, serialize=False)),
                ('desc_tipo_anuncio', models.CharField(max_length=45)),
            ],
            options={
                'db_table': 'tipo_anuncio',
                'managed': False,
            },
        ),
    ]
