# -*- coding: utf-8 -*-
# Generated by Django 1.9 on 2018-10-21 11:22
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('anuncios', '0002_auto_20181018_1359'),
    ]

    operations = [
    ]
